# Use root/example as user/password credentials
version: '3.1'

services:
  hr-app:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: hr-app
    # (this is just an example, not intended to be a production configuration)
